import { Image } from "react-grid-gallery";

export interface CustomImage extends Image {
  original: string;
}

export const images: CustomImage[] = [
  {
    src: "https://imgur.com/CvOq2Ek.png",
    original: "https://imgur.com/CvOq2Ek.png",
    width: 320,
    height: 320,
    tags: [
      { value: "3D", title: "3D" },
      { value: "Blender", title: "Blender" },
    ],
    caption: "Dona 4.0",
  },
  {
    src: "https://imgur.com/FjFhuXC.png",
    original: "https://imgur.com/FjFhuXC.png",
    width: 356,
    height: 200,
    caption: "Chun-Li Kikosho",
  },
  {
    src: "https://imgur.com/jaCabuZ.png",
    original: "https://imgur.com/jaCabuZ.png",
    width: 200,
    height: 356,
    caption: "Chun-Li Victory Pose",
  },
  {
    src: "https://imgur.com/WLcMkQB.png",
    original: "https://imgur.com/WLcMkQB.png",
    width: 320,
    height: 320,
    caption: "Uraraka Manga Style",
  },
  {
    src: "https://imgur.com/nGmKvem.png",
    original: "https://imgur.com/nGmKvem.png",
    width: 200,
    height: 356,
    caption: "Agua de tocador: Double Nature",
  },
  {
    src: "https://imgur.com/059joAs.png",
    original: "https://imgur.com/059joAs.png",
    width: 200,
    height: 356,
    caption: "Agua de tocador: Double Nature",
  },
  {
    src: "https://imgur.com/utO4UPf.png",
    original: "https://imgur.com/utO4UPf.png",
    width: 250,
    height: 356,
    caption: "Muffin",
  },
  {
    src: "https://imgur.com/lMJrSUc.png",
    original: "https://imgur.com/lMJrSUc.png",
    width: 320,
    height: 320,
    caption: "Maquillaje",
  },
  {
    src: "https://imgur.com/521WGxJ.png",
    original: "https://imgur.com/521WGxJ.png",
    width: 200,
    height: 356,
    caption: "Lata de PEPSI",
  },
  {
    src: "https://imgur.com/Q4cRnGK.png",
    original: "https://imgur.com/Q4cRnGK.png",
    width: 200,
    height: 356,
    caption: "Botella de PEPSI",
  },
  {
    src: "https://imgur.com/lyphptu.png",
    original: "https://imgur.com/lyphptu.png",
    width: 200,
    height: 356,
    caption: "Vaso de PEPSI",
  },
  {
    src: "https://imgur.com/Kss7gMZ.png",
    original: "https://imgur.com/Kss7gMZ.png",
    width: 320,
    height: 320,
    caption: "La Bruja",
  },
  {
    src: "https://imgur.com/qShl1Vd.png",
    original: "https://imgur.com/qShl1Vd.png",
    width: 320,
    height: 320,
    caption: "Labial",
  },
  {
    src: "https://imgur.com/ppSvsdk.png",
    original: "https://imgur.com/ppSvsdk.png",
    width: 320,
    height: 320,
    caption: "Personaje propio: Kat",
  },
  {
    src: "https://imgur.com/2STZQAr.png",
    original: "https://imgur.com/2STZQAr.png",
    width: 240,
    height: 320,
    caption: "Dona 3.0",
  },
  {
    src: "https://imgur.com/OvQ129f.png",
    original: "https://imgur.com/OvQ129f.png",
    width: 240,
    height: 320,
    caption: "Flores Amarillas",
  },
  {
    src: "https://imgur.com/dIvTvPv.png",
    original: "https://imgur.com/dIvTvPv.png",
    width: 356,
    height: 200,
    caption: "Libro",
  },
  {
    src: "https://imgur.com/LfmaVvF.png",
    original: "https://imgur.com/LfmaVvF.png",
    width: 356,
    height: 300,
    caption: "Noir City",
  },
  {
    src: "https://imgur.com/G34aZ25.png",
    original: "https://imgur.com/G34aZ25.png",
    width: 320,
    height: 320,
    caption: "Mano sosteniendo casa",
  },
];